---
title: About Me
author: Alexis Ha
date: '2019-12-15'
slug: about-me
categories: []
tags: []
description: ''
---

**HELLO!**

My name is Alexis Ha. I am currently a 4th year Pre-Dental student at the University of Texas at Austin and am planning to graduate with a BS in Human Biology in May 2020. I was born and raised in the Lone Star State (Texas, y'all!) in the Dallas metroplex, which will forever be my home. In my free time, I love spending time with family and close friends, as well as my dog! My love for dogs has led me to volunteering at a local animal shelter, which has made me fall in love with dogs even more, and having been vegan for over 4 years, I have come to have so much more compassion for animals than I ever have. I also love to work out, bake, watch movies, and binge TV shows!

**LEADERSHIP**
Over the course of my college career, I became very involved with a church I joined in Austin. During my sophomore year, I led a ministry called Jesus Cakes, and during my junior year, I became a small group leader. Although these were some of the toughest things I had to endure, they were both very rewarding, especially because my faith and beliefs are very important to me.

**SKILLS**
I am proficient in Microsoft Word and Powerpoint, and have a base-level knowledge of RStudio and Python. I am always willing and happy to be able to learn more and improve my skills!

**ACCOMPLISHMENTS**
In 2018, I was named a College Scholar. College Scholars included students who have completed 60+ hours of coursework and were ranked in the top 20% of their class in their respective colleges, based on GPA.

**CONTACT**
If you have any questions, concerns, comments, or would just like to talk, you can reach me best via email at ajha0606@gmail.com


